export const APP_ENV = {
  PROJECT_ID: process.env.NEXT_PUBLIC_PROJECT_ID as string,
  BACKEND: process.env.NEXT_PUBLIC_BACKEND as string,
  TOKEN_ISSUE_FACTORY_ADDRESS: process.env.NEXT_PUBLIC_TOKEN_ISSUE_FACTORY_ADDRESS as `0x${string}`,
  BAES_TOKEN_ADDRESS: process.env.NEXT_PUBLIC_GOODLE_TOKEN_ADDRESS_BASE as `0x${string}`,
  BASE_SEPOLIA_TOKEN_ADDRESS: process.env
    .NEXT_PUBLIC_GOODLE_TOKEN_ADDRESS_BASE_SEPOLIA as `0x${string}`,
  BASE_STAKING_ADDRESS: process.env.NEXT_PUBLIC_GOODLE_STAKING_ADDRESS_BASE as `0x${string}`,
  BASE_SEPOLIA_STAKING_ADDRESS: process.env
    .NEXT_PUBLIC_GOODLE_STAKING_ADDRESS_BASE_SEPOLIA as `0x${string}`,
  BASE_UNISWAP_ROUTER_ADDRESS: process.env.NEXT_PUBLIC_UNISWAP_ROUTER_BASE as `0x${string}`,
  BASE_SEPOLIA_UNISWAP_ROUTER_ADDRESS: process.env
    .NEXT_PUBLIC_UNISWAP_ROUTER_BASE_SEPOLIA as `0x${string}`,
  ALCHEMY_KEY: process.env.NEXT_PUBLIC_ALCHEMY_KEY,
  MORALIS_KEY: process.env.NEXT_PUBLIC_MORALIS_KEY,
  WALLET_CONNECT_PROJECT_ID: process.env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID,
};
